### ISSUE TITLE
Infuse Your Brilliance into Our Endeavor!

### ISSUE THREAD

**Issue by Kaaveh** [behnawwm/DeveloperPanelPlayground#1]
Hey Behnam, 
This repository contains an amazing idea that can benefit every Android app! If you have the time and are interested, we would be thrilled if you could add this feature to [ComposeNews](https://github.com/Kaaveh/ComposeNews).

**Comment by behnawwm** [comment]
Thanks, Kaveh!
Certainly, I will look into it. Currently, this project needs a bit more experimentation. After that, I would love to contribute.
